import type { Metadata } from "next";
import { Manrope } from "next/font/google";
import Footer from "./Footer";
import NavBar from "./NavBar";
import "./globals.css";

const manrope = Manrope({ subsets: ["latin"], weight: ["700", "500"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <NavBar />

        <main>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
